name: Publish KMM Library

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Extract version from tag
        id: version
        run: |
          TAG_NAME=${GITHUB_REF_NAME}
          VERSION=${TAG_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up GPG
        run: |
          echo "$SIGNING_KEY" | base64 --decode > signingkey.asc
          gpg --batch --import signingkey.asc
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Publish to Maven Central
        run: ./gradlew publishToMavenCentral -PlibraryVersion=${{ steps.version.outputs.version }}
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ✅ Kotlin Multiplatform library released!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
